// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RetailSolution.Data;

namespace RetailSolution.Migrations
{
    [DbContext(typeof(RetailContext))]
    partial class RetailContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("RetailSolution.Models.Employees", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("BaseSalary");

                    b.Property<DateTime>("BirthDate");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("RetailSolution.Models.HoursRegistry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<int>("EmployeesId");

                    b.Property<float>("Friday");

                    b.Property<float>("Hours");

                    b.Property<float>("Monday");

                    b.Property<float>("Saturday");

                    b.Property<bool>("Shift");

                    b.Property<float>("Sunday");

                    b.Property<float>("Thursday");

                    b.Property<float>("Tuesday");

                    b.Property<float>("Wednesday");

                    b.HasKey("Id");

                    b.HasIndex("EmployeesId");

                    b.ToTable("HoursRegistry");
                });

            modelBuilder.Entity("RetailSolution.Models.HoursRegistry", b =>
                {
                    b.HasOne("RetailSolution.Models.Employees", "Employees")
                        .WithMany("HoursRegistry")
                        .HasForeignKey("EmployeesId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
